name: Testing

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Go to the right directory
        run: "cd mental-health-literacy"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run --prefix mental-health-literacy test
